- app.js
- src/App.js
- src/Home.js
- src/store/books.js
- src/store/index.js
added books on the state, fetch books route, and fetch books/setbooks action
> added books on state, fetch books action, and fetch books route

- package-lock.json
- package.json
- src/SignIn.js
- src/User.js
Here is the CSS setup for the Sign In and Sign Up page. The next step is for the Navbar to get changed and added to it. I will next begin to work on the functionality for the SignUp section of this page.
> register/login page is styled and done, need functionality now

- public/styles.css
- src/Home.js
- src/Nav.js
- src/SearchBar.js
> addedSeachComponent

- src/SignIn.js
finished styling login/register i.e space between inputs
> finished styling login register

- src/App.js
- src/IsAdminPanel.js
- src/Nav.js
admins when logged in can see the users table. users who are not admins cannot see the table
> admins see user's table

- app.js
- index.html
- package-lock.json
- package.json
- src/App.js
- src/IsAdminPanel.js
- src/Nav.js
- src/UpdateUserPermissionModal.js
- src/store/auth.js
- src/store/index.js
- src/store/users.js
admins can now grant non-admins admin status
> admin can now give non-admins admin privledges

- app.js
- package-lock.json
- package.json
- public/styles.css
- src/IsAdminPanel.js
- src/UpdateUserPermissionModal.js
> Product user tabs

- app.js
- src/DeleteProductModal.js
- src/DeleteUserModal.js
- src/IsAdminPanel.js
- src/UpdateUserPermissionModal.js
- src/store/users.js
can now delete or update users 
can now delete or update products
> Update delete user product

- app.js
- public/styles.css
- src/AddProduct.js
- src/IsAdminPanel.js
- src/store/books.js
- src/store/users.js
finished admin panel
- update user/delete user
- add product/update product/delete product
> finished admin panel

- src/AddProduct.js
- src/IsAdminPanel.js
> finished-styling-the-admin-console

- app.js
- db/Review.js
- src/Book.js
- src/OrderHistory.js
- src/WriteReview.js
- src/store/reviews.js
> add review

- src/AddProduct.js
- src/Books.js
- src/Home.js
- src/IsAdminPanel.js
- src/NavBar.js
can now upload image to the product when creating it
> upload iamge to new product form done

- db/Product.js
- package-lock.json
- package.json
- src/AddCoupon.js
- src/IsAdminPanel.js
- src/store/books.js
- webpack.config.js
> added coupon modal

- src/Books.js
- src/Home.js
> added styling to home

- src/Home.js
> added banner at bottom of home

- index.html
- package.json
- public/styles.css
- src/Cart.js
- src/Home.js
style changes to checkout page
> style changes to checkout page

- public/styles.css
- src/Cart.js
added more styling to checkout page
> added more styling to checkout page

- src/Cart.js
> initial empty state

- src/Cart.js
- src/OrderHistory.js
> empty state updates

- src/Books.js
- src/SignIn.js
finished styling of the logni/register
> finished styling of the logni/register

- src/IsAdminPanel.js
- src/LineGraphChart.js
> adminStyling

- public/styles.css
- src/Cart.js
> additional cart styling

- public/styles.css
- src/Cart.js
- src/User.js
- src/UserEdit.js
> styling to user details

- src/AddCoupon.js
- src/AddProduct.js
- src/Cart.js
- src/OrderHistory.js
- src/UserAddress.js
- src/UserEdit.js
style changes to multiple files
> style changes to multiple files

- public/styles.css
- src/UserEditPwd.js
stle changes to passwrod update
> stle changes to passwrod update

- src/Cart.js
- src/ConfirmationPage.js
- src/Order.js
- src/SignIn.js
- src/WishList.js
> styling to certain pages

- index.html
- package-lock.json
- package.json
- src/Book.js
- src/SignIn.js
- src/index.js
- src/store/auth.js
- src/store/books.js
- src/store/cart.js
- src/store/index.js
- src/store/orders.js
- src/store/users.js
- src/store/wishList.js
> added notifications

- src/Cart.js
- src/OrderHistory.js
- src/WishList.js
- src/store/auth.js
> additional style changes
